name: InterChat
author: fubira
main: net.ironingot.interchat.InterChatPlugin
version: 0.4.0
commands:
  interchat:
    aliases: [ic]
    permissions: interchat.command
    description: InterChat
    usage:
      /<command> 
      /<command> version
      /<command> reload
      /<command> help
