name: CrossServerChat
author: fubira
main: net.ironingot.crossserverchat.CrossServerChat
version: 0.3
commands:
  crossserverchat:
    aliases: [csc]
    permissions: crossserverchat.command
    description: CrossServerChat
    usage:
      /<command> 
      /<command> version
      /<command> reload
      /<command> help
