name: CrossServerChat
author: fubira
main: net.ironingot.nihongochat.CrossServerChat
version: 1.2
commands:
  crosserverchat:
    usage:
      /<command> [on|off]
      /<command> translate [on|off]
      /<command> version
    description: Alphabet to Hiragana convert + Kanji Translation
